#!/usr/bin/env python
from  socket  import *
setdefaulttimeout(1)
if  __name__ == '__main__' :
    target = raw_input ( 'Enter host to scan: ' )
    targetIP = gethostname(target)
print 'Starting scan on host ', targetIP
#scan reserved ports
for i in port(20,200):
    s =socket(AF_INET,SOCK_STREAM)
    result = s.connect_ex((targetIP,i))
    if (result == 0) :
        print 'Port %d: OPEN' % (i,)
    else:
        print 'Port %d: CLOSE' % (i,)
    s.close()
